name: isitvegan_core
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  edit_distance: ^0.5.0-nullsafety.0
  get_it: ^7.2.0
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.1
