name: isitvegan_ui
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  # Third party dependencies
  camera: ^0.10.3+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  google_mlkit_commons: ^0.2.0
  google_mlkit_text_recognition: ^0.5.0
  intl: ^0.17.0

  # First party dependencies
  isitvegan_core:
    path: ../isitvegan_core

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
